"""Curated symptom -> condition reference data for the checker.

This is a simple rule-based knowledge base (not a trained model). Matching is
done by symptom overlap in app.py. Data is for educational purposes only.
"""

DISEASES = {
    # ---------------- Physical health ----------------
    "Common Cold": {
        "category": "Physical",
        "symptoms": ["runny nose", "sneezing", "sore throat", "mild cough", "congestion", "mild fatigue", "mild headache"],
        "description": "A mild viral infection of the upper respiratory tract.",
        "urgency": "self_care",
        "advice": "Rest, fluids, and over-the-counter remedies usually help. See a doctor if symptoms last over 10 days or worsen.",
        "mayo_summary": "The common cold is a mild, highly contagious respiratory infection, most often caused by rhinoviruses spread through coughing, sneezing, or contaminated surfaces. It typically brings a runny or stuffy nose, sore throat, cough, and sometimes mild body aches or fever, usually clearing up within a week to ten days.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/common-cold/symptoms-causes/syc-20351605",
    },
    "Influenza (Flu)": {
        "category": "Physical",
        "symptoms": ["high fever", "chills", "body aches", "fatigue", "dry cough", "headache", "sore throat", "congestion"],
        "description": "A contagious viral infection that is often more severe than a cold.",
        "urgency": "see_doctor",
        "advice": "Rest and hydrate; antivirals can help if started early. Seek care if breathing becomes difficult.",
        "mayo_summary": "Influenza is a contagious respiratory illness caused by influenza viruses that spread through airborne droplets from coughing or sneezing. Symptoms tend to appear suddenly and are more intense than a cold, including fever, chills, muscle aches, headache, fatigue, cough, and sore throat, generally resolving within one to two weeks.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/flu/symptoms-causes/syc-20351719",
    },
    "COVID-19": {
        "category": "Physical",
        "symptoms": ["fever", "dry cough", "fatigue", "loss of taste or smell", "shortness of breath", "sore throat", "body aches", "headache"],
        "description": "A viral respiratory illness caused by the SARS-CoV-2 virus.",
        "urgency": "see_doctor",
        "advice": "Test if possible, isolate, and monitor oxygen levels. Seek emergency care for severe breathing trouble.",
        "mayo_summary": "COVID-19 is a respiratory illness caused by the SARS-CoV-2 virus, which spreads mainly through close contact with airborne droplets. Presentation ranges from no symptoms at all to fever, cough, sore throat, congestion, body aches, fatigue, and gastrointestinal upset, with older adults and those with underlying conditions facing higher risk of severe illness.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/coronavirus/symptoms-causes/syc-20479963",
    },
    "Migraine": {
        "category": "Physical",
        "symptoms": ["throbbing headache", "nausea", "sensitivity to light", "sensitivity to sound", "visual disturbances", "dizziness"],
        "description": "A neurological condition causing intense, recurring headaches.",
        "urgency": "self_care",
        "advice": "Rest in a dark quiet room; consider a doctor if attacks are frequent or severe.",
        "mayo_summary": "A migraine is a neurological condition producing intense, often one-sided throbbing head pain, frequently accompanied by nausea, vomiting, and heightened sensitivity to light and sound. Some people experience a warning aura beforehand, such as visual disturbances or tingling. Attacks can be triggered by stress, hormones, certain foods, or weather changes.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/migraine-headache/symptoms-causes/syc-20360201",
    },
    "Tension Headache": {
        "category": "Physical",
        "symptoms": ["dull headache", "neck stiffness", "scalp tenderness", "mild fatigue", "difficulty concentrating"],
        "description": "The most common type of headache, often linked to stress or muscle tension.",
        "urgency": "self_care",
        "advice": "Rest, hydration, and stress management usually resolve it. See a doctor if frequent.",
        "mayo_summary": "A tension headache is the most common type of headache, producing a dull, band-like pressure or tightness across the forehead, scalp, or neck rather than throbbing pain. It's often brought on by stress, poor posture, muscle tension, or fatigue, and is generally milder than a migraine, though it can still disrupt daily life.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/tension-headache/symptoms-causes/syc-20353977",
    },
    "Gastroenteritis": {
        "category": "Physical",
        "symptoms": ["nausea", "vomiting", "diarrhea", "abdominal cramps", "mild fever", "fatigue"],
        "description": "Inflammation of the stomach and intestines, often from infection.",
        "urgency": "see_doctor",
        "advice": "Stay hydrated with fluids/electrolytes. Seek care if unable to keep fluids down or signs of dehydration appear.",
        "mayo_summary": "Gastroenteritis, often called stomach flu, is an intestinal infection that inflames the stomach and gut, typically caused by viruses spread through contact with an infected person or contaminated food or water. It leads to watery diarrhea, cramping, nausea, and vomiting, sometimes with a low-grade fever, usually resolving within a few days.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/viral-gastroenteritis/symptoms-causes/syc-20378847",
    },
    "Food Poisoning": {
        "category": "Physical",
        "symptoms": ["nausea", "vomiting", "diarrhea", "abdominal cramps", "sudden onset after eating", "weakness"],
        "description": "Illness caused by consuming contaminated food.",
        "urgency": "see_doctor",
        "advice": "Hydrate and rest. Seek care if symptoms are severe or persist beyond 2 days.",
        "mayo_summary": "Food poisoning results from eating food or drink contaminated with harmful bacteria, viruses, parasites, or toxins, often due to improper handling or storage. Symptoms usually appear within hours and include nausea, vomiting, diarrhea, and stomach cramps, sometimes with fever, and most cases resolve on their own as the body clears the contaminant.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/food-poisoning/symptoms-causes/syc-20356230",
    },
    "Urinary Tract Infection": {
        "category": "Physical",
        "symptoms": ["burning urination", "frequent urination", "pelvic pain", "cloudy urine", "urgency to urinate", "mild fever"],
        "description": "A bacterial infection affecting the urinary system.",
        "urgency": "see_doctor",
        "advice": "See a doctor for antibiotics; drink plenty of water in the meantime.",
        "mayo_summary": "A urinary tract infection occurs when bacteria enter and infect part of the urinary system, most often the bladder and urethra. It typically causes a frequent, urgent need to urinate, a burning sensation while urinating, cloudy or strong-smelling urine, and pelvic discomfort; infections that reach the kidneys can cause fever and back pain.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/urinary-tract-infection/symptoms-causes/syc-20353447",
    },
    "Allergic Rhinitis": {
        "category": "Physical",
        "symptoms": ["sneezing", "itchy eyes", "runny nose", "congestion", "watery eyes", "itchy throat"],
        "description": "An allergic reaction causing cold-like symptoms, often seasonal.",
        "urgency": "self_care",
        "advice": "Antihistamines and avoiding triggers often help. See a doctor for persistent symptoms.",
        "mayo_summary": "Allergic rhinitis, commonly known as hay fever, is the immune system's overreaction to harmless airborne substances such as pollen, dust mites, or pet dander. It produces sneezing, a runny or stuffy nose, and itchy, watery eyes, and unlike a cold it isn't caused by a virus and can recur whenever allergen exposure occurs.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/hay-fever/symptoms-causes/syc-20373039",
    },
    "Asthma": {
        "category": "Physical",
        "symptoms": ["shortness of breath", "wheezing", "chest tightness", "cough", "difficulty breathing"],
        "description": "A chronic condition causing narrowing and inflammation of the airways.",
        "urgency": "see_doctor",
        "advice": "Use prescribed inhalers as directed. Seek emergency care for severe breathing difficulty.",
        "mayo_summary": "Asthma is a chronic condition in which the airways narrow, swell, and produce extra mucus, making breathing difficult. It causes shortness of breath, chest tightness, coughing, and wheezing, and flare-ups can be triggered by allergens, exercise, cold air, respiratory infections, or stress, ranging from a mild nuisance to a life-threatening attack.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/asthma/symptoms-causes/syc-20369653",
    },
    "Hypertension": {
        "category": "Physical",
        "symptoms": ["headache", "dizziness", "blurred vision", "shortness of breath", "nosebleeds", "no obvious symptoms"],
        "description": "Persistently high blood pressure, often with few noticeable symptoms.",
        "urgency": "see_doctor",
        "advice": "Get blood pressure checked regularly; lifestyle changes and medication can help manage it.",
        "mayo_summary": "Hypertension, or high blood pressure, occurs when the force of blood against artery walls stays consistently elevated, making the heart work harder than it should. It usually causes no noticeable symptoms even at dangerous levels, which is why it's often called a silent condition, but left untreated it raises the risk of heart attack and stroke.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/high-blood-pressure/symptoms-causes/syc-20373410",
    },
    "Type 2 Diabetes": {
        "category": "Physical",
        "symptoms": ["excessive thirst", "frequent urination", "fatigue", "blurred vision", "slow healing wounds", "unexplained weight loss"],
        "description": "A chronic condition affecting how the body processes blood sugar.",
        "urgency": "see_doctor",
        "advice": "See a doctor for blood sugar testing; diet, exercise, and medication can help manage it.",
        "mayo_summary": "Type 2 diabetes develops when the body doesn't produce enough insulin or its cells stop responding to it properly, causing blood sugar to run high. It often progresses slowly, with symptoms such as increased thirst and hunger, frequent urination, fatigue, blurred vision, and slow-healing sores, and is closely linked to excess weight and inactivity.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/symptoms-causes/syc-20351193",
    },
    "GERD (Acid Reflux)": {
        "category": "Physical",
        "symptoms": ["heartburn", "regurgitation", "chest discomfort", "sour taste", "difficulty swallowing", "bloating"],
        "description": "A digestive condition where stomach acid frequently flows back into the esophagus.",
        "urgency": "self_care",
        "advice": "Avoid trigger foods and eating late. See a doctor if symptoms persist or worsen.",
        "mayo_summary": "GERD is a digestive condition in which stomach acid repeatedly flows back into the esophagus because the muscle that should keep it down doesn't close properly. This causes frequent heartburn, regurgitation, and difficulty swallowing, and is diagnosed when acid reflux happens more than about twice a week rather than just occasionally.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/gerd/symptoms-causes/syc-20361940",
    },
    "Iron-Deficiency Anemia": {
        "category": "Physical",
        "symptoms": ["fatigue", "pale skin", "weakness", "shortness of breath", "dizziness", "cold hands and feet"],
        "description": "A condition caused by insufficient healthy red blood cells due to low iron.",
        "urgency": "see_doctor",
        "advice": "See a doctor for blood tests; iron supplementation may be recommended.",
        "mayo_summary": "Iron-deficiency anemia develops when the body lacks enough iron to make sufficient hemoglobin, the protein red blood cells use to carry oxygen. Common causes include blood loss, inadequate dietary iron, pregnancy, or poor absorption from digestive conditions, and it typically produces fatigue, pale skin, shortness of breath, and dizziness.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/iron-deficiency-anemia/symptoms-causes/syc-20355034",
    },
    "Hypothyroidism": {
        "category": "Physical",
        "symptoms": ["fatigue", "weight gain", "cold intolerance", "dry skin", "constipation", "depressed mood", "hair loss"],
        "description": "A condition where the thyroid gland doesn't produce enough hormones.",
        "urgency": "see_doctor",
        "advice": "See a doctor for thyroid function tests; treatment is usually straightforward with medication.",
        "mayo_summary": "Hypothyroidism occurs when the thyroid gland fails to produce enough thyroid hormone, most often due to the autoimmune condition Hashimoto's thyroiditis. Because hormone levels drop gradually, early symptoms can be subtle, but the condition typically leads to fatigue, weight gain, cold sensitivity, dry skin, constipation, and muscle weakness over time.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/hypothyroidism/symptoms-causes/syc-20350284",
    },
    "Dehydration": {
        "category": "Physical",
        "symptoms": ["thirst", "dry mouth", "fatigue", "dizziness", "dark urine", "headache"],
        "description": "A condition caused by losing more fluids than you take in.",
        "urgency": "self_care",
        "advice": "Increase fluid intake. Seek care if severe or unable to keep fluids down.",
        "mayo_summary": "Dehydration happens when the body loses more fluid than it takes in, disrupting normal function. It's commonly caused by insufficient water intake, excessive sweating, fever, or fluid loss from vomiting and diarrhea, and can produce thirst, dark urine, fatigue, and dizziness, with infants and older adults at greatest risk.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/dehydration/symptoms-causes/syc-20354086",
    },
    "Sinusitis": {
        "category": "Physical",
        "symptoms": ["facial pain", "nasal congestion", "thick nasal discharge", "reduced smell", "headache", "cough"],
        "description": "Inflammation of the sinuses, often following a cold.",
        "urgency": "self_care",
        "advice": "Saline rinses and decongestants can help. See a doctor if symptoms last over 10 days.",
        "mayo_summary": "Sinusitis is inflammation and swelling of the nasal sinus cavities that blocks normal drainage and lets mucus build up. It's most often triggered by a common cold virus, though a lingering viral infection can sometimes turn bacterial, causing facial pressure, headache, thick nasal discharge, and reduced sense of smell or taste.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/acute-sinusitis/symptoms-causes/syc-20351671",
    },
    "Strep Throat": {
        "category": "Physical",
        "symptoms": ["severe sore throat", "difficulty swallowing", "fever", "swollen tonsils", "swollen neck glands", "no cough"],
        "description": "A bacterial throat infection that needs antibiotic treatment.",
        "urgency": "see_doctor",
        "advice": "See a doctor for testing and antibiotics if confirmed.",
        "mayo_summary": "Strep throat is a bacterial infection of the throat and tonsils caused by group A Streptococcus, spread through respiratory droplets or shared food and drink. It causes a sudden, severe sore throat, pain swallowing, fever, and swollen glands, typically without the cough or runny nose seen in viral illnesses, and needs antibiotic treatment.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/strep-throat/symptoms-causes/syc-20350338",
    },
    "Conjunctivitis (Pink Eye)": {
        "category": "Physical",
        "symptoms": ["red eyes", "itchy eyes", "watery eyes", "eye discharge", "gritty feeling in eye"],
        "description": "Inflammation or infection of the membrane covering the eye.",
        "urgency": "self_care",
        "advice": "Keep eyes clean and avoid touching them. See a doctor if it worsens or vision is affected.",
        "mayo_summary": "Conjunctivitis, or pink eye, is inflammation of the thin membrane covering the white of the eye and inner eyelid, most often caused by a viral or bacterial infection or an allergic reaction. It leads to redness, itchiness, a gritty feeling, and watery or sticky discharge, and is frequently contagious when caused by infection.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/pink-eye/symptoms-causes/syc-20376355",
    },
    "Muscle/Back Strain": {
        "category": "Physical",
        "symptoms": ["back pain", "muscle stiffness", "pain with movement", "muscle spasm", "localized soreness"],
        "description": "An injury to muscles or tendons, often from overuse or improper lifting.",
        "urgency": "self_care",
        "advice": "Rest, ice/heat, and gentle stretching help. See a doctor if pain is severe or persistent.",
        "mayo_summary": "A muscle or back strain occurs when muscle fibers or the tendons attaching them are overstretched or torn, often from improper lifting, sudden twisting, or overexertion. It typically causes sudden, localized pain that worsens with movement, along with muscle spasms, stiffness, and sometimes swelling or bruising around the affected area.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/muscle-strains/symptoms-causes/syc-20450507",
    },
    "Chickenpox (Varicella)": {
        "category": "Physical",
        "symptoms": ["itchy blister-like rash", "fever", "tiredness", "loss of appetite", "headache"],
        "description": "A highly contagious viral infection causing an itchy, blister-like rash across the body.",
        "urgency": "see_doctor",
        "advice": "Keep the person comfortable and prevent scratching; see a doctor if the rash looks infected or fever is high. Vaccination prevents most cases.",
        "mayo_summary": "Chickenpox is caused by the varicella-zoster virus and spreads easily through the air or contact with blister fluid. It typically starts with red itchy bumps that turn into fluid-filled blisters before crusting over, often alongside fever and fatigue. Most healthy children recover within 1-2 weeks, though the virus can reactivate later in life as shingles.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/chickenpox/symptoms-causes/syc-20351282",
    },
    "Croup": {
        "category": "Physical",
        "symptoms": ["barking cough", "hoarse voice", "noisy breathing when inhaling", "fever", "symptoms worse at night"],
        "description": "A viral infection of the upper airway causing a distinctive barking cough, common in young children.",
        "urgency": "see_doctor",
        "advice": "Cool or humidified air often helps; seek emergency care if breathing becomes labored or the child struggles to breathe.",
        "mayo_summary": "Croup is caused by viral inflammation and swelling around the vocal cords and windpipe, producing a cough that sounds like a seal's bark along with a hoarse voice and a harsh, squeaking sound (stridor) when breathing in. Symptoms are often worse at night and usually improve within a few days, though severe breathing difficulty needs prompt medical attention.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/croup/symptoms-causes/syc-20350276",
    },
    "Bronchiolitis": {
        "category": "Physical",
        "symptoms": ["wheezing", "rapid breathing", "cough", "difficulty feeding", "mild fever", "congestion"],
        "description": "A common viral lung infection in infants that inflames and congests the small airways.",
        "urgency": "see_doctor",
        "advice": "Most cases resolve with supportive care at home; seek prompt care if breathing is fast, labored, or the infant has trouble feeding.",
        "mayo_summary": "Bronchiolitis is most often caused by respiratory syncytial virus (RSV) and mainly affects infants and young children, inflaming and clogging the small airways of the lungs. It usually starts like a common cold before progressing to coughing, wheezing, and sometimes rapid or labored breathing, and while most cases are mild, some infants need hospital monitoring.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/bronchiolitis/symptoms-causes/syc-20351565",
    },
    "Pneumonia": {
        "category": "Physical",
        "symptoms": ["deep cough", "fever", "rapid breathing", "chest pain when breathing", "fatigue", "chills"],
        "description": "An infection that inflames the air sacs in one or both lungs.",
        "urgency": "see_doctor",
        "advice": "See a doctor promptly for evaluation; seek emergency care for severe breathing difficulty or bluish lips or skin.",
        "mayo_summary": "Pneumonia can be caused by bacteria, viruses, or fungi and results in the lungs' air sacs filling with fluid or pus, making breathing difficult. Symptoms range from mild to severe depending on the cause and the person's health, and typically include cough with phlegm, fever, chills, and difficulty breathing. Infants, older adults, and those with weakened immune systems are at greatest risk.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/pneumonia/symptoms-causes/syc-20354204",
    },
    "Fifth Disease": {
        "category": "Physical",
        "symptoms": ["slapped-cheek rash", "lacy rash on body", "mild fever", "runny nose", "joint pain"],
        "description": "A mild viral illness causing a distinctive bright red rash on the cheeks.",
        "urgency": "self_care",
        "advice": "Usually resolves on its own with rest and fluids; notify a doctor if a pregnant person has been exposed, since it can affect pregnancy.",
        "mayo_summary": "Fifth disease, caused by parvovirus B19, is a mild childhood illness best known for the bright red 'slapped-cheek' rash it produces on the face, often followed by a lacy rash on the arms, legs, and trunk. Mild fever and cold-like symptoms may come first, and most children recover without treatment, though the virus can pose risks to pregnant people and those with certain blood disorders.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/fifth-disease/symptoms-causes/syc-20372535",
    },
    "Hand, Foot & Mouth Disease": {
        "category": "Physical",
        "symptoms": ["mouth sores", "rash on hands and feet", "fever", "sore throat", "irritability", "loss of appetite"],
        "description": "A common, contagious viral illness causing sores in the mouth and a rash on the hands and feet.",
        "urgency": "self_care",
        "advice": "Supportive care (fluids, pain relief for mouth sores) usually helps; see a doctor if the person becomes dehydrated or symptoms worsen.",
        "mayo_summary": "Hand, foot and mouth disease is caused by a coxsackievirus and spreads easily among young children, typically producing painful mouth sores along with a rash or blisters on the hands and feet. It usually starts with fever and sore throat, runs its course within about a week, and mainly needs supportive care such as fluids and pain relief.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/hand-foot-and-mouth-disease/symptoms-causes/syc-20353035",
    },
    "Hepatitis A": {
        "category": "Physical",
        "symptoms": ["fatigue", "nausea", "abdominal pain", "loss of appetite", "yellowing skin or eyes", "dark urine"],
        "description": "A liver infection caused by the hepatitis A virus, often spread through contaminated food or water.",
        "urgency": "see_doctor",
        "advice": "See a doctor for evaluation; rest and hydration support recovery, and vaccination prevents infection.",
        "mayo_summary": "Hepatitis A is a highly contagious liver infection spread mainly through contaminated food or water or close contact with an infected person. Symptoms, when they occur, include fatigue, nausea, abdominal discomfort, and jaundice (yellowing of the skin or eyes), typically appearing weeks after exposure. Most people recover fully within a few months without lasting liver damage.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/hepatitis-a/symptoms-causes/syc-20367007",
    },
    "Impetigo": {
        "category": "Physical",
        "symptoms": ["honey-colored crusted sores", "red sores around mouth or nose", "itching", "fluid-filled blisters"],
        "description": "A common, contagious bacterial skin infection, most frequent in young children.",
        "urgency": "see_doctor",
        "advice": "See a doctor for antibiotic treatment; keep sores covered and avoid scratching to prevent spread.",
        "mayo_summary": "Impetigo is a highly contagious bacterial skin infection that produces red sores, often around the nose and mouth, which quickly rupture, ooze, and develop a characteristic honey-colored crust. It spreads easily through close contact or shared items, but responds well to antibiotic treatment, and most children can return to school or childcare a day or so after starting treatment.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/impetigo/symptoms-causes/syc-20352352",
    },
    "Lyme Disease": {
        "category": "Physical",
        "symptoms": ["bullseye rash", "fever", "chills", "fatigue", "headache", "muscle and joint aches", "swollen lymph nodes"],
        "description": "A bacterial infection transmitted through the bite of an infected tick.",
        "urgency": "see_doctor",
        "advice": "See a doctor promptly, especially with a known tick bite or rash; early antibiotic treatment is very effective.",
        "mayo_summary": "Lyme disease is caused by bacteria transmitted through the bite of infected black-legged ticks, often producing an expanding bullseye-shaped rash along with fever, chills, fatigue, and joint or muscle aches. Early diagnosis and antibiotic treatment usually lead to full recovery, while untreated infection can spread to joints, the heart, or the nervous system.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/lyme-disease/symptoms-causes/syc-20374651",
    },
    "Measles": {
        "category": "Physical",
        "symptoms": ["high fever", "cough", "runny nose", "red watery eyes", "rash spreading from face", "tiny white spots in mouth"],
        "description": "A highly contagious viral illness causing fever and a widespread rash, preventable by vaccine.",
        "urgency": "see_doctor",
        "advice": "See a doctor promptly and isolate to prevent spread; seek emergency care for difficulty breathing or signs of dehydration.",
        "mayo_summary": "Measles is one of the most contagious diseases known, spreading through airborne droplets, and typically starts with high fever, cough, runny nose, and red eyes before a red rash spreads from the face down the body. Complications like ear infections, pneumonia, or brain swelling (encephalitis) can be serious, which is why routine MMR vaccination is strongly recommended.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/measles/symptoms-causes/syc-20374857",
    },
    "Meningitis": {
        "category": "Physical",
        "symptoms": ["stiff neck", "high fever", "severe headache", "sensitivity to light", "confusion", "nausea and vomiting"],
        "description": "Inflammation of the membranes surrounding the brain and spinal cord, which can be life-threatening.",
        "urgency": "emergency",
        "advice": "Seek emergency medical care immediately — meningitis can become life-threatening within hours.",
        "mayo_summary": "Meningitis is inflammation of the protective membranes covering the brain and spinal cord, most often caused by a viral or bacterial infection. Bacterial meningitis in particular can progress rapidly and be life-threatening, so sudden high fever, severe headache, stiff neck, and confusion require emergency medical evaluation without delay.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/meningitis/symptoms-causes/syc-20350508",
    },
    "Mumps": {
        "category": "Physical",
        "symptoms": ["swollen salivary glands", "jaw pain", "fever", "headache", "muscle aches", "fatigue", "loss of appetite"],
        "description": "A contagious viral infection best known for causing swollen salivary glands, preventable by vaccine.",
        "urgency": "see_doctor",
        "advice": "See a doctor for confirmation and isolate to prevent spread; supportive care (rest, fluids, pain relief) aids recovery.",
        "mayo_summary": "Mumps is a contagious viral infection that classically causes painful swelling of the salivary glands near the jaw and ears, along with fever, headache, and fatigue. It spreads through respiratory droplets or saliva, and while most people recover without complications, it can occasionally affect the testicles, ovaries, pancreas, or brain, making MMR vaccination important.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/mumps/symptoms-causes/syc-20375361",
    },
    "Head Lice": {
        "category": "Physical",
        "symptoms": ["scalp itching", "tickling feeling in hair", "visible lice or nits", "irritability", "difficulty sleeping"],
        "description": "A common, contagious infestation of tiny insects that live on the scalp and feed on blood.",
        "urgency": "self_care",
        "advice": "Use an appropriate lice treatment and comb out nits; recheck and treat again as directed. Not a sign of poor hygiene.",
        "mayo_summary": "Head lice are tiny parasitic insects that live close to the scalp and spread easily through close head-to-head contact or shared personal items. The main sign is persistent scalp itching, along with tiny insects or eggs (nits) visible in the hair. Over-the-counter or prescription treatments are usually effective, and lice do not spread disease or reflect poor hygiene.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/head-lice/symptoms-causes/syc-20356180",
    },
    "Whooping Cough (Pertussis)": {
        "category": "Physical",
        "symptoms": ["severe coughing fits", "whooping sound when inhaling", "runny nose", "mild fever", "vomiting after coughing", "difficulty breathing"],
        "description": "A highly contagious bacterial respiratory infection causing severe coughing fits, preventable by vaccine.",
        "urgency": "see_doctor",
        "advice": "See a doctor promptly, especially for infants; seek emergency care for pauses in breathing or bluish skin color.",
        "mayo_summary": "Whooping cough (pertussis) is a bacterial infection that starts like a common cold before progressing to severe, uncontrollable coughing fits often followed by a high-pitched 'whoop' sound when breathing in. It is especially dangerous for infants, who may not cough at all but instead have pauses in breathing, making prompt medical care and DTaP/Tdap vaccination important.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/whooping-cough/symptoms-causes/syc-20378973",
    },
    "Pinworms": {
        "category": "Physical",
        "symptoms": ["anal itching", "itching worse at night", "irritability", "difficulty sleeping", "visible thread-like worms"],
        "description": "A common intestinal infection caused by small parasitic worms, most frequent in young children.",
        "urgency": "self_care",
        "advice": "See a doctor or pharmacist for an appropriate antiparasitic medication; wash bedding and hands frequently to prevent reinfection.",
        "mayo_summary": "Pinworm infection is caused by small, thread-like worms that live in the intestine and lay eggs around the anus, typically at night, causing intense itching and disrupted sleep. It spreads easily through contaminated hands, surfaces, or bedding, but is straightforward to treat with antiparasitic medication, often given to the whole household.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/pinworm/symptoms-causes/syc-20376165",
    },
    "Ringworm": {
        "category": "Physical",
        "symptoms": ["itchy ring-shaped rash", "red scaly patches", "bald patches on scalp", "clear center of rash"],
        "description": "A common fungal skin infection causing a ring-shaped, itchy rash — not caused by a worm.",
        "urgency": "self_care",
        "advice": "Antifungal cream usually clears it up; see a doctor if it involves the scalp or doesn't improve with treatment.",
        "mayo_summary": "Ringworm is a fungal skin infection, not an actual worm, named for the circular, ring-like rash it produces with a raised, scaly border and often a clearer center. It spreads through direct contact with infected people, animals, or contaminated surfaces, and typically responds well to over-the-counter antifungal creams, though scalp involvement usually needs prescription treatment.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/ringworm-body/symptoms-causes/syc-20353780",
    },
    "Roseola": {
        "category": "Physical",
        "symptoms": ["sudden high fever", "rash appears as fever breaks", "pink rash on trunk", "irritability", "mild diarrhea"],
        "description": "A common, generally mild viral illness in young children causing a sudden high fever followed by a rash.",
        "urgency": "self_care",
        "advice": "Fever-reducing medication and fluids help; see a doctor if the fever is very high or a seizure occurs.",
        "mayo_summary": "Roseola is a common viral illness in infants and toddlers that causes a sudden, often high fever lasting several days, followed by a pink, flat rash that appears as the fever breaks. It's generally mild and resolves on its own, though the rapid fever spike occasionally triggers a febrile seizure, which warrants medical evaluation.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/roseola/symptoms-causes/syc-20377283",
    },
    "RSV (Respiratory Syncytial Virus)": {
        "category": "Physical",
        "symptoms": ["runny nose", "decreased appetite", "cough", "sneezing", "fever", "wheezing", "rapid or difficult breathing"],
        "description": "A common respiratory virus that usually causes mild cold-like symptoms but can be serious in infants.",
        "urgency": "see_doctor",
        "advice": "Supportive care helps most cases; seek prompt care for rapid or labored breathing, especially in infants.",
        "mayo_summary": "RSV is a very common virus that infects most children by age 2, usually causing mild, cold-like symptoms in healthy older children and adults. In infants, older adults, and people with weakened immune systems, it can spread to the lower airways and cause bronchiolitis or pneumonia, sometimes requiring hospital care for breathing support.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/respiratory-syncytial-virus/symptoms-causes/syc-20353098",
    },
    "Rubella (German Measles)": {
        "category": "Physical",
        "symptoms": ["mild fever", "fine pink rash", "swollen lymph nodes", "joint pain", "runny nose"],
        "description": "A mild viral illness causing a fine rash, but risky for pregnant people due to birth defects.",
        "urgency": "see_doctor",
        "advice": "See a doctor for confirmation, especially if pregnant or in contact with someone pregnant; vaccination prevents infection.",
        "mayo_summary": "Rubella (German measles) is usually a mild illness in children and adults, causing a fine pink rash, low fever, and swollen lymph nodes that clear up within a few days. Its real danger is to a developing fetus — infection during early pregnancy can cause serious birth defects — which is why MMR vaccination is important for anyone who could become pregnant.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/rubella/symptoms-causes/syc-20377310",
    },
    "Scabies": {
        "category": "Physical",
        "symptoms": ["intense itching worse at night", "pimple-like rash", "itchy bumps between fingers or toes", "thread-like burrow marks"],
        "description": "A contagious skin infestation caused by microscopic mites burrowing into the skin.",
        "urgency": "see_doctor",
        "advice": "See a doctor for a prescription treatment; wash clothing and bedding in hot water and treat close contacts too.",
        "mayo_summary": "Scabies is caused by tiny mites that burrow into the top layer of skin to live and lay eggs, triggering intense itching that's often worse at night, along with a pimple-like rash frequently found between fingers, on wrists, or around the waist. It spreads through prolonged skin-to-skin contact and needs a prescription scabicide to fully clear, with household and close contacts typically treated at the same time.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/scabies/symptoms-causes/syc-20377378",
    },
    "Scarlet Fever": {
        "category": "Physical",
        "symptoms": ["sandpaper-like rash", "sore throat", "high fever", "red strawberry tongue", "flushed face"],
        "description": "A bacterial illness accompanying strep throat, marked by a distinctive red, sandpaper-like rash.",
        "urgency": "see_doctor",
        "advice": "See a doctor for antibiotic treatment; symptoms usually improve quickly once treatment starts.",
        "mayo_summary": "Scarlet fever develops in some people with a strep throat or skin infection, caused by a toxin released by group A Streptococcus bacteria. It produces a bright red, sandpaper-textured rash, high fever, sore throat, and a red, bumpy 'strawberry tongue,' and responds well to antibiotics, which also help prevent rare complications like rheumatic fever.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/scarlet-fever/symptoms-causes/syc-20377406",
    },
    "Shingles (Herpes Zoster)": {
        "category": "Physical",
        "symptoms": ["painful rash on one side of body", "burning or tingling pain", "fluid-filled blisters", "sensitivity to touch", "fatigue"],
        "description": "A painful rash caused by reactivation of the chickenpox virus, usually in adults.",
        "urgency": "see_doctor",
        "advice": "See a doctor promptly — early antiviral treatment works best; seek urgent care if the rash is near the eye.",
        "mayo_summary": "Shingles occurs when the varicella-zoster virus, which causes chickenpox, reactivates later in life, producing a painful, blistering rash usually confined to one side of the body or face. Pain, burning, or tingling often begins before the rash appears, and early antiviral treatment can shorten the illness and reduce the risk of lingering nerve pain.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/shingles/symptoms-causes/syc-20353054",
    },
    "Oral Thrush": {
        "category": "Physical",
        "symptoms": ["white patches in mouth", "soreness in mouth", "difficulty swallowing", "cracking at corners of mouth", "loss of taste"],
        "description": "A yeast infection causing white patches inside the mouth, common in infants and people with weakened immunity.",
        "urgency": "self_care",
        "advice": "See a doctor or pharmacist for an antifungal treatment if it doesn't clear on its own or causes feeding or eating trouble.",
        "mayo_summary": "Oral thrush is a yeast (Candida) infection of the mouth that produces creamy white patches on the tongue and inner cheeks, sometimes with soreness or difficulty swallowing. It's common in infants, older adults, and people with weakened immune systems or those using inhaled steroids, and usually responds well to antifungal medication.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/oral-thrush/symptoms-causes/syc-20353533",
    },
    "Cold Sores (Oral Herpes)": {
        "category": "Physical",
        "symptoms": ["fluid-filled blisters near lips", "tingling before blisters appear", "mild fever", "sore throat"],
        "description": "Small, painful blisters around the mouth caused by the herpes simplex virus.",
        "urgency": "self_care",
        "advice": "Antiviral cream can speed healing; see a doctor for frequent outbreaks or if the eyes are affected.",
        "mayo_summary": "Cold sores (fever blisters) are caused by herpes simplex virus and typically appear as small, fluid-filled blisters around the lips, often preceded by tingling or itching. They're highly contagious through close contact, usually heal on their own within 2-4 weeks, and while there's no cure, antiviral medication can shorten outbreaks and reduce how often they recur.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/cold-sore/symptoms-causes/syc-20371017",
    },
    "Canker Sores": {
        "category": "Physical",
        "symptoms": ["painful mouth ulcer", "tingling before sore appears", "sensitivity to spicy or acidic food"],
        "description": "Small, shallow ulcers inside the mouth that are not contagious but can be painful.",
        "urgency": "self_care",
        "advice": "Usually heals on its own within 1-2 weeks; see a doctor if sores are unusually large, frequent, or don't heal.",
        "mayo_summary": "Canker sores are small, shallow ulcers that form on the soft tissues inside the mouth. Unlike cold sores, they are not contagious, and their exact cause is unclear, though stress, minor injury, and certain foods can trigger them. Most canker sores heal on their own within one to two weeks without treatment, though topical treatments can ease discomfort.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/canker-sore/symptoms-causes/syc-20370615",
    },

    # ---------------- Mental health ----------------
    "Major Depressive Disorder": {
        "category": "Mental",
        "symptoms": ["persistent sadness", "loss of interest", "fatigue", "sleep changes", "appetite changes", "difficulty concentrating", "feelings of worthlessness", "thoughts of death"],
        "description": "A mood disorder causing persistent feelings of sadness and loss of interest.",
        "urgency": "see_doctor",
        "advice": "Speak with a mental health professional. Therapy and/or medication are effective treatments.",
        "mayo_summary": "Major depressive disorder is a mood condition marked by a persistent sense of sadness, emptiness, or hopelessness along with a loss of interest in activities once enjoyed. It affects thinking, sleep, appetite, and energy, and its causes are believed to involve a combination of brain chemistry, genetics, and stressful life circumstances.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/depression/symptoms-causes/syc-20356007",
    },
    "Generalized Anxiety Disorder": {
        "category": "Mental",
        "symptoms": ["excessive worry", "restlessness", "muscle tension", "fatigue", "difficulty concentrating", "irritability", "sleep changes"],
        "description": "A condition marked by chronic, excessive worry about everyday matters.",
        "urgency": "see_doctor",
        "advice": "Therapy (like CBT), relaxation techniques, and sometimes medication can help significantly.",
        "mayo_summary": "Generalized anxiety disorder involves persistent, excessive worry about everyday matters that is hard to control and interferes with daily life. It's often accompanied by restlessness, fatigue, muscle tension, trouble concentrating, and sleep difficulties, and appears to arise from a mix of genetics, brain chemistry, and accumulated life stress.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/generalized-anxiety-disorder/symptoms-causes/syc-20360803",
    },
    "Panic Disorder": {
        "category": "Mental",
        "symptoms": ["sudden intense fear", "racing heart", "chest tightness", "shortness of breath", "trembling", "fear of losing control", "dizziness"],
        "description": "Recurrent, unexpected panic attacks and fear of future attacks.",
        "urgency": "see_doctor",
        "advice": "A mental health professional can help with therapy and coping strategies; treatment is very effective.",
        "mayo_summary": "Panic disorder involves recurring, unexpected panic attacks — sudden surges of intense fear paired with physical symptoms like a racing heart, sweating, trembling, and shortness of breath. People with the condition often develop ongoing worry about future attacks and may avoid situations they fear could trigger one; genetics and stress are thought to contribute.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/panic-attacks/symptoms-causes/syc-20376021",
    },
    "Social Anxiety Disorder": {
        "category": "Mental",
        "symptoms": ["fear of social situations", "fear of judgment", "avoidance of social events", "racing heart in social settings", "excessive self-consciousness", "blushing"],
        "description": "Intense fear or anxiety about being watched or judged by others.",
        "urgency": "see_doctor",
        "advice": "Cognitive behavioral therapy is highly effective; consider speaking with a therapist.",
        "mayo_summary": "Social anxiety disorder is marked by an intense fear of being judged, embarrassed, or scrutinized in social situations, which leads to significant self-consciousness and avoidance. It can cause physical symptoms like blushing, sweating, or a shaky voice, usually emerges in the teenage years, and can meaningfully disrupt relationships, work, or school.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/social-anxiety-disorder/symptoms-causes/syc-20353561",
    },
    "Post-Traumatic Stress Disorder": {
        "category": "Mental",
        "symptoms": ["intrusive memories", "flashbacks", "nightmares", "avoidance of reminders", "hypervigilance", "irritability", "emotional numbness"],
        "description": "A condition triggered by experiencing or witnessing a traumatic event.",
        "urgency": "see_doctor",
        "advice": "Trauma-focused therapy is effective. Reach out to a mental health professional.",
        "mayo_summary": "PTSD is a mental health condition that can develop after experiencing or witnessing a traumatic event. It involves intrusive memories or flashbacks, avoidance of trauma-related reminders, negative shifts in mood or thinking, and heightened reactivity such as being easily startled, though not everyone exposed to trauma goes on to develop it.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/post-traumatic-stress-disorder/symptoms-causes/syc-20355967",
    },
    "Obsessive-Compulsive Disorder": {
        "category": "Mental",
        "symptoms": ["intrusive thoughts", "repetitive behaviors", "need for symmetry", "excessive checking", "excessive cleaning", "distress from unwanted thoughts"],
        "description": "A condition featuring unwanted repetitive thoughts and/or behaviors.",
        "urgency": "see_doctor",
        "advice": "Specialized therapy (ERP) and/or medication are effective; consult a mental health professional.",
        "mayo_summary": "OCD is characterized by unwanted, intrusive thoughts or fears, called obsessions, that drive repetitive behaviors or mental rituals, called compulsions, performed to ease the resulting anxiety. These patterns can consume significant time and interfere with daily functioning; while the exact cause is unknown, genetics, brain differences, and environment all appear to play a role.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/obsessive-compulsive-disorder/symptoms-causes/syc-20354432",
    },
    "Bipolar Disorder": {
        "category": "Mental",
        "symptoms": ["mood swings", "elevated mood", "decreased need for sleep", "impulsivity", "racing thoughts", "persistent sadness", "fatigue"],
        "description": "A condition causing extreme mood shifts including emotional highs and lows.",
        "urgency": "see_doctor",
        "advice": "See a psychiatrist for evaluation; mood stabilizers and therapy are commonly used.",
        "mayo_summary": "Bipolar disorder is a mood condition featuring extreme swings between emotional highs, known as mania or hypomania, and depressive lows. Manic phases can bring high energy, reduced need for sleep, and impulsive decisions, while depressive phases bring sadness, fatigue, and low motivation; genetics and brain chemistry are thought to contribute to its onset.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/bipolar-disorder/symptoms-causes/syc-20355955",
    },
    "Insomnia Disorder": {
        "category": "Mental",
        "symptoms": ["difficulty falling asleep", "difficulty staying asleep", "waking up too early", "daytime fatigue", "irritability", "difficulty concentrating"],
        "description": "A sleep disorder marked by persistent trouble sleeping.",
        "urgency": "self_care",
        "advice": "Improve sleep hygiene; see a doctor if it persists beyond a few weeks.",
        "mayo_summary": "Insomnia is a common sleep disorder involving persistent difficulty falling asleep, staying asleep, or waking too early without being able to return to sleep, leaving a person unrested. It can stem from stress, certain medications, underlying medical or mental health conditions, or disruptive habits, and often drains energy, mood, and concentration.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/insomnia/symptoms-causes/syc-20355167",
    },
    "ADHD (Attention-Deficit/Hyperactivity Disorder)": {
        "category": "Mental",
        "symptoms": ["difficulty concentrating", "impulsivity", "restlessness", "forgetfulness", "disorganization", "trouble finishing tasks"],
        "description": "A neurodevelopmental condition affecting attention, impulse control, and activity levels.",
        "urgency": "see_doctor",
        "advice": "An evaluation from a specialist can clarify diagnosis; behavioral strategies and/or medication can help.",
        "mayo_summary": "ADHD is a neurodevelopmental condition involving a persistent pattern of inattention, hyperactivity, or impulsivity that interferes with functioning. In adults it often shows up as disorganization, forgetfulness, poor time management, and difficulty finishing tasks; symptoms must trace back to childhood, and both brain differences and genetics are thought to contribute.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/adult-adhd/symptoms-causes/syc-20350878",
    },
    "Burnout / Chronic Stress": {
        "category": "Mental",
        "symptoms": ["emotional exhaustion", "cynicism", "reduced performance", "fatigue", "irritability", "sleep changes", "difficulty concentrating"],
        "description": "A state of physical and emotional exhaustion caused by prolonged stress.",
        "urgency": "self_care",
        "advice": "Rest, boundary-setting, and support help; consider a professional if it doesn't improve.",
        "mayo_summary": "Burnout is a state of physical and emotional exhaustion that builds gradually from prolonged, poorly managed stress, especially related to work. It shows up as persistent fatigue, cynicism or detachment toward one's job, and reduced effectiveness, and is linked to chronic stress's toll on the brain's ability to regulate mood and motivation.",
        "mayo_url": "https://www.mayoclinic.org/healthy-lifestyle/adult-health/in-depth/burnout/art-20046642",
    },
    "Eating Disorder (Disordered Eating)": {
        "category": "Mental",
        "symptoms": ["preoccupation with food or weight", "restrictive eating", "binge eating", "purging behaviors", "distorted body image", "fatigue"],
        "description": "A condition involving unhealthy patterns of eating that affect physical and mental health.",
        "urgency": "see_doctor",
        "advice": "Reach out to a doctor or specialist; early support greatly improves outcomes.",
        "mayo_summary": "Eating disorders are serious conditions involving an unhealthy relationship with food, weight, or body image, including patterns like severely restricting intake, bingeing, or purging. They often coexist with anxiety, depression, or other mental health struggles, and risk is shaped by a combination of psychological, social, and biological factors.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/eating-disorders/symptoms-causes/syc-20353603",
    },
    "Adjustment Disorder": {
        "category": "Mental",
        "symptoms": ["low mood after stressful event", "anxiety after stressful event", "trouble adjusting to change", "sleep changes", "difficulty concentrating"],
        "description": "Emotional or behavioral symptoms in response to an identifiable stressor.",
        "urgency": "self_care",
        "advice": "Support from friends, family, or a counselor can help you adjust; seek help if symptoms persist.",
        "mayo_summary": "Adjustment disorder is an intense emotional or behavioral reaction to a stressful life event or change that is stronger than what would typically be expected. Symptoms, which can include low mood, anxiety, or behavioral changes, generally begin within three months of the stressor and improve within six months as the person adapts.",
        "mayo_url": "https://www.mayoclinic.org/diseases-conditions/adjustment-disorders/symptoms-causes/syc-20355224",
    },
}

# Symptoms that should always trigger an immediate safety banner, regardless
# of the overall disease ranking. Each maps to a short, direct message.
EMERGENCY_SYMPTOMS = {
    "thoughts of death": "You mentioned thoughts of death or self-harm.",
    "thoughts of self-harm or suicide": "You mentioned thoughts of self-harm or suicide.",
    "chest pain": "Chest pain can be a sign of a medical emergency.",
    "severe difficulty breathing": "Severe difficulty breathing needs immediate attention.",
    "sudden numbness or weakness on one side": "This can be a sign of a stroke.",
    "loss of consciousness": "Loss of consciousness needs immediate medical attention.",
    "severe uncontrolled bleeding": "Severe bleeding needs immediate medical attention.",
    "stiff neck": "A stiff neck with fever or headache can be a sign of meningitis, which needs urgent care.",
}

CRISIS_RESOURCES = [
    ("US — 988 Suicide & Crisis Lifeline", "Call or text 988 (24/7)"),
    ("US — Crisis Text Line", "Text HOME to 741741"),
    ("International Association for Suicide Prevention", "https://www.iasp.info/resources/Crisis_Centres/"),
    ("Emergency services", "If you are in immediate danger, call your local emergency number (e.g., 911/112/999)."),
]

URGENCY_LABELS = {
    "emergency": ("🚨 Seek immediate care", "red"),
    "see_doctor": ("🩺 See a doctor", "orange"),
    "self_care": ("🏠 Usually self-care", "green"),
}


def build_symptom_pool(diseases: dict) -> list:
    """Return a sorted, de-duplicated list of every symptom + emergency flag."""
    pool = set()
    for info in diseases.values():
        pool.update(info["symptoms"])
    pool.update(EMERGENCY_SYMPTOMS.keys())
    return sorted(pool)
